"""Seed data — 500+ companies with career page URLs."""

COMPANIES = [
    # === GLOBAL TECH GIANTS (India presence) ===
    {"name": "Google", "careers_url": "https://careers.google.com", "category": "tech_giants", "country": "Global"},
    {"name": "Microsoft", "careers_url": "https://careers.microsoft.com", "category": "tech_giants", "country": "Global"},
    {"name": "Amazon", "careers_url": "https://www.amazon.jobs", "category": "tech_giants", "country": "Global"},
    {"name": "Meta", "careers_url": "https://www.metacareers.com", "category": "tech_giants", "country": "Global"},
    {"name": "Apple", "careers_url": "https://jobs.apple.com", "category": "tech_giants", "country": "Global"},
    {"name": "Salesforce", "careers_url": "https://careers.salesforce.com", "category": "tech_giants", "country": "Global"},
    {"name": "Oracle", "careers_url": "https://careers.oracle.com", "category": "tech_giants", "country": "Global"},
    {"name": "SAP", "careers_url": "https://jobs.sap.com", "category": "tech_giants", "country": "Global"},
    {"name": "IBM", "careers_url": "https://www.ibm.com/careers", "category": "tech_giants", "country": "Global"},
    {"name": "Nvidia", "careers_url": "https://www.nvidia.com/en-us/about-nvidia/careers", "category": "tech_giants", "country": "Global"},
    {"name": "Adobe", "careers_url": "https://careers.adobe.com", "category": "tech_giants", "country": "Global"},
    {"name": "Intel", "careers_url": "https://jobs.intel.com", "category": "tech_giants", "country": "Global"},
    {"name": "Cisco", "careers_url": "https://jobs.cisco.com", "category": "tech_giants", "country": "Global"},
    {"name": "Dell", "careers_url": "https://jobs.dell.com", "category": "tech_giants", "country": "Global"},
    {"name": "HP", "careers_url": "https://jobs.hp.com", "category": "tech_giants", "country": "Global"},
    {"name": "VMware", "careers_url": "https://careers.vmware.com", "category": "tech_giants", "country": "Global"},
    {"name": "Qualcomm", "careers_url": "https://careers.qualcomm.com", "category": "tech_giants", "country": "Global"},
    {"name": "Texas Instruments", "careers_url": "https://careers.ti.com", "category": "tech_giants", "country": "Global"},
    {"name": "Broadcom", "careers_url": "https://www.broadcom.com/company/careers", "category": "tech_giants", "country": "Global"},
    {"name": "ServiceNow", "careers_url": "https://careers.servicenow.com", "category": "tech_giants", "country": "Global"},
    # === AI COMPANIES ===
    {"name": "OpenAI", "careers_url": "https://openai.com/careers", "category": "ai_companies", "country": "Global"},
    {"name": "Anthropic", "careers_url": "https://www.anthropic.com/careers", "category": "ai_companies", "country": "Global"},
    {"name": "Scale AI", "careers_url": "https://scale.com/careers", "category": "ai_companies", "country": "Global"},
    {"name": "Databricks", "careers_url": "https://www.databricks.com/company/careers", "category": "ai_companies", "country": "Global"},
    {"name": "Hugging Face", "careers_url": "https://huggingface.co/jobs", "category": "ai_companies", "country": "Global"},
    {"name": "Cohere", "careers_url": "https://cohere.com/careers", "category": "ai_companies", "country": "Global"},
    {"name": "Mistral AI", "careers_url": "https://mistral.ai/careers", "category": "ai_companies", "country": "Global"},
    {"name": "Runway", "careers_url": "https://runwayml.com/careers", "category": "ai_companies", "country": "Global"},
    {"name": "Stability AI", "careers_url": "https://stability.ai/careers", "category": "ai_companies", "country": "Global"},
    {"name": "Perplexity AI", "careers_url": "https://www.perplexity.ai/hub/careers", "category": "ai_companies", "country": "Global"},
    # === CLOUD & SAAS ===
    {"name": "Snowflake", "careers_url": "https://careers.snowflake.com", "category": "cloud_saas", "country": "Global"},
    {"name": "Atlassian", "careers_url": "https://www.atlassian.com/company/careers", "category": "cloud_saas", "country": "Global"},
    {"name": "Stripe", "careers_url": "https://stripe.com/jobs", "category": "cloud_saas", "country": "Global"},
    {"name": "Twilio", "careers_url": "https://www.twilio.com/company/jobs", "category": "cloud_saas", "country": "Global"},
    {"name": "Notion", "careers_url": "https://www.notion.so/careers", "category": "cloud_saas", "country": "Global"},
    {"name": "Figma", "careers_url": "https://www.figma.com/careers", "category": "cloud_saas", "country": "Global"},
    {"name": "Canva", "careers_url": "https://www.canva.com/careers", "category": "cloud_saas", "country": "Global"},
    {"name": "Slack", "careers_url": "https://slack.com/careers", "category": "cloud_saas", "country": "Global"},
    {"name": "Zoom", "careers_url": "https://careers.zoom.us", "category": "cloud_saas", "country": "Global"},
    {"name": "Shopify", "careers_url": "https://www.shopify.com/careers", "category": "cloud_saas", "country": "Global"},
    {"name": "HubSpot", "careers_url": "https://www.hubspot.com/careers", "category": "cloud_saas", "country": "Global"},
    {"name": "MongoDB", "careers_url": "https://www.mongodb.com/careers", "category": "cloud_saas", "country": "Global"},
    {"name": "Elastic", "careers_url": "https://www.elastic.co/careers", "category": "cloud_saas", "country": "Global"},
    {"name": "Confluent", "careers_url": "https://www.confluent.io/careers", "category": "cloud_saas", "country": "Global"},
    {"name": "HashiCorp", "careers_url": "https://www.hashicorp.com/careers", "category": "cloud_saas", "country": "Global"},
    # === CONSULTING ===
    {"name": "McKinsey", "careers_url": "https://www.mckinsey.com/careers", "category": "consulting", "country": "Global"},
    {"name": "BCG", "careers_url": "https://careers.bcg.com", "category": "consulting", "country": "Global"},
    {"name": "Bain", "careers_url": "https://www.bain.com/careers", "category": "consulting", "country": "Global"},
    {"name": "Deloitte", "careers_url": "https://apply.deloitte.com", "category": "consulting", "country": "Global"},
    {"name": "Accenture", "careers_url": "https://www.accenture.com/us-en/careers", "category": "consulting", "country": "Global"},
    {"name": "EY", "careers_url": "https://www.ey.com/en_in/careers", "category": "consulting", "country": "India"},
    {"name": "PwC", "careers_url": "https://www.pwc.in/careers.html", "category": "consulting", "country": "India"},
    {"name": "KPMG", "careers_url": "https://kpmg.com/in/en/home/careers.html", "category": "consulting", "country": "India"},
    # === INDIAN IT SERVICES ===
    {"name": "TCS", "careers_url": "https://www.tcs.com/careers", "category": "it_services", "country": "India"},
    {"name": "Infosys", "careers_url": "https://www.infosys.com/careers/", "category": "it_services", "country": "India"},
    {"name": "Wipro", "careers_url": "https://careers.wipro.com/", "category": "it_services", "country": "India"},
    {"name": "HCLTech", "careers_url": "https://www.hcltech.com/careers", "category": "it_services", "country": "India"},
    {"name": "Tech Mahindra", "careers_url": "https://careers.techmahindra.com/", "category": "it_services", "country": "India"},
    {"name": "LTIMindtree", "careers_url": "https://www.ltimindtree.com/careers/", "category": "it_services", "country": "India"},
    {"name": "Persistent Systems", "careers_url": "https://careers.persistent.com/", "category": "it_services", "country": "India"},
    {"name": "Mphasis", "careers_url": "https://careers.mphasis.com/", "category": "it_services", "country": "India"},
    {"name": "Coforge", "careers_url": "https://www.coforge.com/careers", "category": "it_services", "country": "India"},
    {"name": "Zensar Technologies", "careers_url": "https://www.zensar.com/careers", "category": "it_services", "country": "India"},
    {"name": "Cyient", "careers_url": "https://www.cyient.com/careers", "category": "it_services", "country": "India"},
    {"name": "NIIT Technologies", "careers_url": "https://www.niit-tech.com/careers", "category": "it_services", "country": "India"},
    {"name": "Hexaware", "careers_url": "https://hexaware.com/careers/", "category": "it_services", "country": "India"},
    {"name": "Birlasoft", "careers_url": "https://www.birlasoft.com/careers", "category": "it_services", "country": "India"},
    {"name": "Sonata Software", "careers_url": "https://www.sonata-software.com/careers", "category": "it_services", "country": "India"},
    {"name": "Happiest Minds", "careers_url": "https://www.happiestminds.com/careers/", "category": "it_services", "country": "India"},
    {"name": "Mastek", "careers_url": "https://www.mastek.com/careers/", "category": "it_services", "country": "India"},
    # === INDIAN STARTUPS & UNICORNS ===
    {"name": "Flipkart", "careers_url": "https://www.flipkartcareers.com/", "category": "indian_startups", "country": "India"},
    {"name": "Razorpay", "careers_url": "https://razorpay.com/careers/", "category": "indian_startups", "country": "India"},
    {"name": "CRED", "careers_url": "https://careers.cred.club/", "category": "indian_startups", "country": "India"},
    {"name": "Zerodha", "careers_url": "https://zerodha.com/careers/", "category": "indian_startups", "country": "India"},
    {"name": "PhonePe", "careers_url": "https://www.phonepe.com/careers/", "category": "indian_startups", "country": "India"},
    {"name": "Swiggy", "careers_url": "https://careers.swiggy.com/", "category": "indian_startups", "country": "India"},
    {"name": "Zomato", "careers_url": "https://www.zomato.com/careers", "category": "indian_startups", "country": "India"},
    {"name": "Ola", "careers_url": "https://www.olacabs.com/careers", "category": "indian_startups", "country": "India"},
    {"name": "Paytm", "careers_url": "https://paytm.com/careers/", "category": "indian_startups", "country": "India"},
    {"name": "Byju's", "careers_url": "https://byjus.com/careers/", "category": "indian_startups", "country": "India"},
    {"name": "Unacademy", "careers_url": "https://unacademy.com/careers", "category": "indian_startups", "country": "India"},
    {"name": "UpGrad", "careers_url": "https://www.upgrad.com/careers/", "category": "indian_startups", "country": "India"},
    {"name": "Meesho", "careers_url": "https://meesho.io/careers", "category": "indian_startups", "country": "India"},
    {"name": "Groww", "careers_url": "https://groww.in/careers", "category": "indian_startups", "country": "India"},
    {"name": "Lenskart", "careers_url": "https://www.lenskart.com/careers", "category": "indian_startups", "country": "India"},
    {"name": "Nykaa", "careers_url": "https://www.nykaa.com/careers", "category": "indian_startups", "country": "India"},
    {"name": "Dream11", "careers_url": "https://www.dreamsports.group/careers", "category": "indian_startups", "country": "India"},
    {"name": "Freshworks", "careers_url": "https://www.freshworks.com/careers/", "category": "indian_startups", "country": "India"},
    {"name": "Zoho", "careers_url": "https://www.zoho.com/careers/", "category": "indian_startups", "country": "India"},
    {"name": "Postman", "careers_url": "https://www.postman.com/careers/", "category": "indian_startups", "country": "India"},
    {"name": "BrowserStack", "careers_url": "https://www.browserstack.com/careers", "category": "indian_startups", "country": "India"},
    {"name": "Chargebee", "careers_url": "https://www.chargebee.com/careers/", "category": "indian_startups", "country": "India"},
    {"name": "CleverTap", "careers_url": "https://clevertap.com/careers/", "category": "indian_startups", "country": "India"},
    {"name": "WebEngage", "careers_url": "https://webengage.com/careers/", "category": "indian_startups", "country": "India"},
    {"name": "MoEngage", "careers_url": "https://www.moengage.com/careers/", "category": "indian_startups", "country": "India"},
    {"name": "Mindtickle", "careers_url": "https://www.mindtickle.com/careers/", "category": "indian_startups", "country": "India"},
    {"name": "Darwinbox", "careers_url": "https://www.darwinbox.com/careers", "category": "indian_startups", "country": "India"},
    {"name": "Leadsquared", "careers_url": "https://www.leadsquared.com/careers/", "category": "indian_startups", "country": "India"},
    {"name": "Druva", "careers_url": "https://www.druva.com/careers/", "category": "indian_startups", "country": "India"},
    {"name": "Hasura", "careers_url": "https://hasura.io/careers/", "category": "indian_startups", "country": "India"},
    {"name": "Razorpay", "careers_url": "https://razorpay.com/careers/", "category": "indian_startups", "country": "India"},
    {"name": "Slice", "careers_url": "https://www.sliceit.com/careers", "category": "indian_startups", "country": "India"},
    {"name": "Jupiter", "careers_url": "https://jupiter.money/careers/", "category": "indian_startups", "country": "India"},
    {"name": "Fi Money", "careers_url": "https://fi.money/careers", "category": "indian_startups", "country": "India"},
    {"name": "Jar", "careers_url": "https://www.myjar.app/careers", "category": "indian_startups", "country": "India"},
    {"name": "Delhivery", "careers_url": "https://www.delhivery.com/careers/", "category": "indian_startups", "country": "India"},
    {"name": "Shiprocket", "careers_url": "https://www.shiprocket.in/careers/", "category": "indian_startups", "country": "India"},
    {"name": "Dunzo", "careers_url": "https://www.dunzo.com/careers", "category": "indian_startups", "country": "India"},
    {"name": "Urban Company", "careers_url": "https://www.urbancompany.com/careers", "category": "indian_startups", "country": "India"},
    {"name": "Practo", "careers_url": "https://www.practo.com/careers", "category": "indian_startups", "country": "India"},
    {"name": "1mg", "careers_url": "https://www.1mg.com/careers", "category": "indian_startups", "country": "India"},
    {"name": "PharmEasy", "careers_url": "https://pharmeasy.in/careers", "category": "indian_startups", "country": "India"},
    {"name": "Cure.fit", "careers_url": "https://www.cult.fit/careers", "category": "indian_startups", "country": "India"},
    {"name": "Spinny", "careers_url": "https://www.spinny.com/careers/", "category": "indian_startups", "country": "India"},
    {"name": "Cars24", "careers_url": "https://www.cars24.com/careers/", "category": "indian_startups", "country": "India"},
    {"name": "CarDekho", "careers_url": "https://www.cardekho.com/careers", "category": "indian_startups", "country": "India"},
    # === INDIAN FINTECH ===
    {"name": "Pine Labs", "careers_url": "https://www.pinelabs.com/careers", "category": "fintech", "country": "India"},
    {"name": "BharatPe", "careers_url": "https://www.bharatpe.com/careers", "category": "fintech", "country": "India"},
    {"name": "Policybazaar", "careers_url": "https://careers.policybazaar.com/", "category": "fintech", "country": "India"},
    {"name": "Paytm Money", "careers_url": "https://paytm.com/careers/", "category": "fintech", "country": "India"},
    {"name": "Niyo", "careers_url": "https://www.goniyo.com/careers/", "category": "fintech", "country": "India"},
    {"name": "KreditBee", "careers_url": "https://www.kreditbee.in/careers", "category": "fintech", "country": "India"},
    {"name": "Rupeek", "careers_url": "https://www.rupeek.com/careers", "category": "fintech", "country": "India"},
    {"name": "Lendingkart", "careers_url": "https://www.lendingkart.com/careers/", "category": "fintech", "country": "India"},
    {"name": "Khatabook", "careers_url": "https://khatabook.com/careers", "category": "fintech", "country": "India"},
    {"name": "Open Financial", "careers_url": "https://open.money/careers", "category": "fintech", "country": "India"},
    {"name": "Perfios", "careers_url": "https://www.perfios.com/careers/", "category": "fintech", "country": "India"},
    {"name": "Signzy", "careers_url": "https://signzy.com/careers/", "category": "fintech", "country": "India"},
    # === INDIAN CONGLOMERATES ===
    {"name": "Reliance Industries", "careers_url": "https://careers.ril.com/", "category": "conglomerates", "country": "India"},
    {"name": "Tata Group", "careers_url": "https://www.tata.com/careers", "category": "conglomerates", "country": "India"},
    {"name": "Mahindra Group", "careers_url": "https://careers.mahindra.com/", "category": "conglomerates", "country": "India"},
    {"name": "Adani Group", "careers_url": "https://www.adani.com/careers", "category": "conglomerates", "country": "India"},
    {"name": "Aditya Birla Group", "careers_url": "https://careers.adityabirla.com/", "category": "conglomerates", "country": "India"},
    {"name": "Godrej", "careers_url": "https://careers.godrej.com/", "category": "conglomerates", "country": "India"},
    {"name": "Larsen & Toubro", "careers_url": "https://www.larsentoubro.com/careers/", "category": "conglomerates", "country": "India"},
    {"name": "ITC", "careers_url": "https://www.itcportal.com/careers/", "category": "conglomerates", "country": "India"},
    {"name": "Bajaj Group", "careers_url": "https://www.bajajfinserv.in/careers", "category": "conglomerates", "country": "India"},
    {"name": "Hero Group", "careers_url": "https://www.heromotocorp.com/en-in/careers.html", "category": "conglomerates", "country": "India"},
    # === INDIAN BANKS & FINANCIAL ===
    {"name": "HDFC Bank", "careers_url": "https://www.hdfcbank.com/personal/about-us/careers", "category": "banking", "country": "India"},
    {"name": "ICICI Bank", "careers_url": "https://www.icicicareers.com/", "category": "banking", "country": "India"},
    {"name": "Kotak Mahindra", "careers_url": "https://www.kotak.com/en/careers.html", "category": "banking", "country": "India"},
    {"name": "Axis Bank", "careers_url": "https://www.axisbank.com/careers", "category": "banking", "country": "India"},
    {"name": "SBI", "careers_url": "https://www.sbi.co.in/web/careers", "category": "banking", "country": "India"},
    {"name": "Yes Bank", "careers_url": "https://www.yesbank.in/about-us/careers", "category": "banking", "country": "India"},
    {"name": "IndusInd Bank", "careers_url": "https://www.indusind.com/in/en/careers.html", "category": "banking", "country": "India"},
    {"name": "Federal Bank", "careers_url": "https://www.federalbank.co.in/careers", "category": "banking", "country": "India"},
    {"name": "Bajaj Finance", "careers_url": "https://www.bajajfinserv.in/careers", "category": "banking", "country": "India"},
    # === INDIAN AI & DEEPTECH ===
    {"name": "Ola Krutrim", "careers_url": "https://www.olakrutrim.com/careers", "category": "ai_india", "country": "India"},
    {"name": "Sarvam AI", "careers_url": "https://www.sarvam.ai/careers", "category": "ai_india", "country": "India"},
    {"name": "Fractal Analytics", "careers_url": "https://fractal.ai/careers/", "category": "ai_india", "country": "India"},
    {"name": "Mu Sigma", "careers_url": "https://www.mu-sigma.com/careers", "category": "ai_india", "country": "India"},
    {"name": "Tiger Analytics", "careers_url": "https://www.tigeranalytics.com/careers/", "category": "ai_india", "country": "India"},
    {"name": "LatentView Analytics", "careers_url": "https://www.latentview.com/careers/", "category": "ai_india", "country": "India"},
    {"name": "Sigmoid", "careers_url": "https://www.sigmoid.com/careers/", "category": "ai_india", "country": "India"},
    {"name": "ThoughtSpot", "careers_url": "https://www.thoughtspot.com/careers", "category": "ai_india", "country": "India"},
    {"name": "Observe.AI", "careers_url": "https://www.observe.ai/careers", "category": "ai_india", "country": "India"},
    {"name": "Yellow.ai", "careers_url": "https://yellow.ai/careers/", "category": "ai_india", "country": "India"},
    {"name": "Haptik", "careers_url": "https://www.haptik.ai/careers", "category": "ai_india", "country": "India"},
    {"name": "Uniphore", "careers_url": "https://www.uniphore.com/careers/", "category": "ai_india", "country": "India"},
    {"name": "SigTuple", "careers_url": "https://sigtuple.com/careers/", "category": "ai_india", "country": "India"},
    {"name": "Niramai", "careers_url": "https://www.niramai.com/careers/", "category": "ai_india", "country": "India"},
    {"name": "Mad Street Den", "careers_url": "https://www.madstreetden.com/careers/", "category": "ai_india", "country": "India"},
    # === INDIAN ECOMMERCE & D2C ===
    {"name": "Myntra", "careers_url": "https://www.myntra.com/careers", "category": "ecommerce", "country": "India"},
    {"name": "Snapdeal", "careers_url": "https://www.snapdeal.com/page/careers", "category": "ecommerce", "country": "India"},
    {"name": "FirstCry", "careers_url": "https://www.firstcry.com/careers", "category": "ecommerce", "country": "India"},
    {"name": "BigBasket", "careers_url": "https://www.bigbasket.com/careers/", "category": "ecommerce", "country": "India"},
    {"name": "BlinkIt", "careers_url": "https://blinkit.com/careers", "category": "ecommerce", "country": "India"},
    {"name": "Zepto", "careers_url": "https://www.zeptonow.com/careers", "category": "ecommerce", "country": "India"},
    {"name": "Purplle", "careers_url": "https://www.purplle.com/careers", "category": "ecommerce", "country": "India"},
    {"name": "Mamaearth", "careers_url": "https://mamaearth.in/careers", "category": "ecommerce", "country": "India"},
    {"name": "boAt", "careers_url": "https://www.boat-lifestyle.com/pages/careers", "category": "ecommerce", "country": "India"},
    {"name": "Sugar Cosmetics", "careers_url": "https://www.sugarcosmetics.com/careers", "category": "ecommerce", "country": "India"},
    # === INDIAN EDTECH ===
    {"name": "Scaler", "careers_url": "https://www.scaler.com/careers/", "category": "edtech", "country": "India"},
    {"name": "Physics Wallah", "careers_url": "https://www.physicswallah.live/careers", "category": "edtech", "country": "India"},
    {"name": "Vedantu", "careers_url": "https://www.vedantu.com/careers", "category": "edtech", "country": "India"},
    {"name": "Simplilearn", "careers_url": "https://www.simplilearn.com/careers", "category": "edtech", "country": "India"},
    {"name": "Great Learning", "careers_url": "https://www.greatlearning.in/careers", "category": "edtech", "country": "India"},
    {"name": "Eruditus", "careers_url": "https://www.eruditus.com/careers/", "category": "edtech", "country": "India"},
    {"name": "Testbook", "careers_url": "https://testbook.com/careers", "category": "edtech", "country": "India"},
    # === INDIAN HEALTHTECH ===
    {"name": "Pristyn Care", "careers_url": "https://www.pristyncare.com/careers/", "category": "healthtech", "country": "India"},
    {"name": "MFine", "careers_url": "https://www.mfine.co/careers/", "category": "healthtech", "country": "India"},
    {"name": "Innovaccer", "careers_url": "https://innovaccer.com/careers/", "category": "healthtech", "country": "India"},
    {"name": "Dozee", "careers_url": "https://www.dozee.io/careers/", "category": "healthtech", "country": "India"},
    # === INDIAN SAAS ===
    {"name": "Whatfix", "careers_url": "https://whatfix.com/careers/", "category": "saas_india", "country": "India"},
    {"name": "Wingify", "careers_url": "https://wingify.com/careers/", "category": "saas_india", "country": "India"},
    {"name": "Hevo Data", "careers_url": "https://hevodata.com/careers/", "category": "saas_india", "country": "India"},
    {"name": "Razorpay", "careers_url": "https://razorpay.com/careers/", "category": "saas_india", "country": "India"},
    {"name": "Freshworks", "careers_url": "https://www.freshworks.com/careers/", "category": "saas_india", "country": "India"},
    {"name": "Capillary Technologies", "careers_url": "https://www.capillarytech.com/careers/", "category": "saas_india", "country": "India"},
    {"name": "Netcore Cloud", "careers_url": "https://netcorecloud.com/careers/", "category": "saas_india", "country": "India"},
    {"name": "Gupshup", "careers_url": "https://www.gupshup.io/careers", "category": "saas_india", "country": "India"},
    {"name": "Eka Software", "careers_url": "https://eka1.com/careers/", "category": "saas_india", "country": "India"},
    # === GLOBAL COMPANIES WITH INDIA OFFICES ===
    {"name": "Samsung India", "careers_url": "https://www.samsung.com/in/about-us/careers/", "category": "mnc_india", "country": "India"},
    {"name": "Uber India", "careers_url": "https://www.uber.com/in/en/careers/", "category": "mnc_india", "country": "India"},
    {"name": "Goldman Sachs India", "careers_url": "https://www.goldmansachs.com/careers/", "category": "mnc_india", "country": "India"},
    {"name": "JP Morgan India", "careers_url": "https://careers.jpmorgan.com/", "category": "mnc_india", "country": "India"},
    {"name": "Morgan Stanley India", "careers_url": "https://www.morganstanley.com/careers/", "category": "mnc_india", "country": "India"},
    {"name": "Barclays India", "careers_url": "https://search.jobs.barclays/", "category": "mnc_india", "country": "India"},
    {"name": "Deutsche Bank India", "careers_url": "https://careers.db.com/", "category": "mnc_india", "country": "India"},
    {"name": "Mastercard India", "careers_url": "https://careers.mastercard.com/", "category": "mnc_india", "country": "India"},
    {"name": "Visa India", "careers_url": "https://usa.visa.com/careers.html", "category": "mnc_india", "country": "India"},
    {"name": "PayPal India", "careers_url": "https://careers.pypl.com/", "category": "mnc_india", "country": "India"},
    {"name": "Walmart India", "careers_url": "https://careers.walmart.com/", "category": "mnc_india", "country": "India"},
    {"name": "Target India", "careers_url": "https://india.target.com/", "category": "mnc_india", "country": "India"},
    {"name": "Siemens India", "careers_url": "https://jobs.siemens.com/", "category": "mnc_india", "country": "India"},
    {"name": "Bosch India", "careers_url": "https://www.bosch.in/careers/", "category": "mnc_india", "country": "India"},
    {"name": "ABB India", "careers_url": "https://careers.abb/", "category": "mnc_india", "country": "India"},
    {"name": "Schneider Electric India", "careers_url": "https://www.se.com/in/en/about-us/careers/", "category": "mnc_india", "country": "India"},
    {"name": "Honeywell India", "careers_url": "https://careers.honeywell.com/", "category": "mnc_india", "country": "India"},
    {"name": "GE India", "careers_url": "https://www.ge.com/careers", "category": "mnc_india", "country": "India"},
    {"name": "Philips India", "careers_url": "https://www.careers.philips.com/", "category": "mnc_india", "country": "India"},
    {"name": "Ericsson India", "careers_url": "https://www.ericsson.com/en/careers", "category": "mnc_india", "country": "India"},
    {"name": "Nokia India", "careers_url": "https://www.nokia.com/careers/", "category": "mnc_india", "country": "India"},
    # === INDIAN MEDIA & ENTERTAINMENT ===
    {"name": "Hotstar", "careers_url": "https://careers.hotstar.com/", "category": "media", "country": "India"},
    {"name": "Jio", "careers_url": "https://careers.jio.com/", "category": "media", "country": "India"},
    {"name": "ShareChat", "careers_url": "https://sharechat.com/careers", "category": "media", "country": "India"},
    {"name": "InMobi", "careers_url": "https://www.inmobi.com/careers", "category": "media", "country": "India"},
    {"name": "Glance", "careers_url": "https://www.glance.com/careers", "category": "media", "country": "India"},
    {"name": "Dailyhunt", "careers_url": "https://www.dailyhunt.in/careers", "category": "media", "country": "India"},
    # === INDIAN LOGISTICS & MOBILITY ===
    {"name": "Rivigo", "careers_url": "https://www.rivigo.com/careers/", "category": "logistics", "country": "India"},
    {"name": "BlackBuck", "careers_url": "https://www.blackbuck.com/careers", "category": "logistics", "country": "India"},
    {"name": "Rapido", "careers_url": "https://rapido.bike/careers", "category": "logistics", "country": "India"},
    {"name": "Ather Energy", "careers_url": "https://www.atherenergy.com/careers", "category": "logistics", "country": "India"},
    {"name": "Ola Electric", "careers_url": "https://www.olaelectric.com/careers", "category": "logistics", "country": "India"},
    # === INDIAN REAL ESTATE TECH ===
    {"name": "NoBroker", "careers_url": "https://www.nobroker.in/careers", "category": "proptech", "country": "India"},
    {"name": "Housing.com", "careers_url": "https://housing.com/careers", "category": "proptech", "country": "India"},
    {"name": "Square Yards", "careers_url": "https://www.squareyards.com/careers", "category": "proptech", "country": "India"},
    {"name": "Magicbricks", "careers_url": "https://www.magicbricks.com/careers", "category": "proptech", "country": "India"},
    # === INDIAN GAMING ===
    {"name": "MPL", "careers_url": "https://www.mpl.live/careers", "category": "gaming", "country": "India"},
    {"name": "Games24x7", "careers_url": "https://www.games24x7.com/careers/", "category": "gaming", "country": "India"},
    {"name": "Nazara Technologies", "careers_url": "https://www.nazara.com/careers", "category": "gaming", "country": "India"},
    # === INDIAN TRAVEL ===
    {"name": "MakeMyTrip", "careers_url": "https://careers.makemytrip.com/", "category": "travel", "country": "India"},
    {"name": "Cleartrip", "careers_url": "https://www.cleartrip.com/careers", "category": "travel", "country": "India"},
    {"name": "ixigo", "careers_url": "https://www.ixigo.com/careers", "category": "travel", "country": "India"},
    {"name": "OYO", "careers_url": "https://www.oyorooms.com/careers/", "category": "travel", "country": "India"},
    {"name": "Yatra", "careers_url": "https://www.yatra.com/careers", "category": "travel", "country": "India"},
    # === INDIAN AGRITECH & OTHERS ===
    {"name": "DeHaat", "careers_url": "https://www.dehaat.com/careers", "category": "agritech", "country": "India"},
    {"name": "Ninjacart", "careers_url": "https://www.ninjacart.com/careers", "category": "agritech", "country": "India"},
    {"name": "Stashfin", "careers_url": "https://www.stashfin.com/careers", "category": "fintech", "country": "India"},
    {"name": "Zetwerk", "careers_url": "https://www.zetwerk.com/careers/", "category": "manufacturing", "country": "India"},
    {"name": "Moglix", "careers_url": "https://www.moglix.com/careers", "category": "manufacturing", "country": "India"},
    {"name": "Udaan", "careers_url": "https://udaan.com/careers", "category": "b2b", "country": "India"},
    {"name": "OfBusiness", "careers_url": "https://www.ofbusiness.com/careers", "category": "b2b", "country": "India"},
    {"name": "Apna", "careers_url": "https://apna.co/careers", "category": "hrtech", "country": "India"},
    {"name": "Keka", "careers_url": "https://www.keka.com/careers", "category": "hrtech", "country": "India"},
    {"name": "Pocket FM", "careers_url": "https://pocketfm.com/careers", "category": "media", "country": "India"},
    {"name": "Kuku FM", "careers_url": "https://kukufm.com/careers", "category": "media", "country": "India"},
    # === PHASE 3: NEW API-VERIFIED COMPANIES ===
    # Global AI & ML
    {"name": "xAI", "careers_url": "https://x.ai/careers", "category": "ai_companies", "country": "Global"},
    {"name": "DeepMind", "careers_url": "https://deepmind.google/careers/", "category": "ai_companies", "country": "Global"},
    {"name": "LangChain", "careers_url": "https://langchain.com/careers", "category": "ai_companies", "country": "Global"},
    {"name": "LlamaIndex", "careers_url": "https://llamaindex.ai/careers", "category": "ai_companies", "country": "Global"},
    {"name": "Together AI", "careers_url": "https://together.ai/careers", "category": "ai_companies", "country": "Global"},
    {"name": "Anyscale", "careers_url": "https://anyscale.com/careers", "category": "ai_companies", "country": "Global"},
    {"name": "Modal", "careers_url": "https://modal.com/careers", "category": "ai_companies", "country": "Global"},
    {"name": "Pinecone", "careers_url": "https://pinecone.io/careers", "category": "ai_companies", "country": "Global"},
    {"name": "Weaviate", "careers_url": "https://weaviate.io/careers", "category": "ai_companies", "country": "Global"},
    {"name": "Labelbox", "careers_url": "https://labelbox.com/careers", "category": "ai_companies", "country": "Global"},
    {"name": "Semgrep", "careers_url": "https://semgrep.dev/careers", "category": "ai_companies", "country": "Global"},
    {"name": "Dust", "careers_url": "https://dust.tt/careers", "category": "ai_companies", "country": "Global"},
    {"name": "Coframe", "careers_url": "https://coframe.ai/careers", "category": "ai_companies", "country": "Global"},
    {"name": "Airbyte", "careers_url": "https://airbyte.com/careers", "category": "ai_companies", "country": "Global"},
    # Global Cloud & DevTools
    {"name": "Cloudflare", "careers_url": "https://www.cloudflare.com/careers/", "category": "cloud_saas", "country": "Global"},
    {"name": "Datadog", "careers_url": "https://www.datadoghq.com/careers/", "category": "cloud_saas", "country": "Global"},
    {"name": "Vercel", "careers_url": "https://vercel.com/careers", "category": "cloud_saas", "country": "Global"},
    {"name": "Fastly", "careers_url": "https://www.fastly.com/careers", "category": "cloud_saas", "country": "Global"},
    {"name": "New Relic", "careers_url": "https://newrelic.com/careers", "category": "cloud_saas", "country": "Global"},
    {"name": "PlanetScale", "careers_url": "https://planetscale.com/careers", "category": "cloud_saas", "country": "Global"},
    {"name": "Neon", "careers_url": "https://neon.tech/careers", "category": "cloud_saas", "country": "Global"},
    {"name": "Webflow", "careers_url": "https://webflow.com/careers", "category": "cloud_saas", "country": "Global"},
    {"name": "Bubble", "careers_url": "https://bubble.io/careers", "category": "cloud_saas", "country": "Global"},
    {"name": "Linear", "careers_url": "https://linear.app/careers", "category": "cloud_saas", "country": "Global"},
    {"name": "PostHog", "careers_url": "https://posthog.com/careers", "category": "cloud_saas", "country": "Global"},
    {"name": "LiveKit", "careers_url": "https://livekit.io/careers", "category": "cloud_saas", "country": "Global"},
    {"name": "Superblocks", "careers_url": "https://superblocks.com/careers", "category": "cloud_saas", "country": "Global"},
    # Global SaaS & Business
    {"name": "Asana", "careers_url": "https://asana.com/jobs", "category": "cloud_saas", "country": "Global"},
    {"name": "Airtable", "careers_url": "https://airtable.com/careers", "category": "cloud_saas", "country": "Global"},
    {"name": "Smartsheet", "careers_url": "https://www.smartsheet.com/careers", "category": "cloud_saas", "country": "Global"},
    {"name": "Calendly", "careers_url": "https://calendly.com/careers", "category": "cloud_saas", "country": "Global"},
    {"name": "Intercom", "careers_url": "https://www.intercom.com/careers", "category": "cloud_saas", "country": "Global"},
    {"name": "Brex", "careers_url": "https://brex.com/careers", "category": "cloud_saas", "country": "Global"},
    {"name": "Ramp", "careers_url": "https://ramp.com/careers", "category": "cloud_saas", "country": "Global"},
    {"name": "Deel", "careers_url": "https://deel.com/careers", "category": "cloud_saas", "country": "Global"},
    {"name": "Oyster", "careers_url": "https://oysterhr.com/careers", "category": "cloud_saas", "country": "Global"},
    {"name": "Lattice", "careers_url": "https://lattice.com/careers", "category": "cloud_saas", "country": "Global"},
    {"name": "Leapsome", "careers_url": "https://leapsome.com/careers", "category": "cloud_saas", "country": "Global"},
    {"name": "15Five", "careers_url": "https://15five.com/careers", "category": "cloud_saas", "country": "Global"},
    {"name": "Gong", "careers_url": "https://www.gong.io/careers", "category": "cloud_saas", "country": "Global"},
    {"name": "Clari", "careers_url": "https://clari.com/careers", "category": "cloud_saas", "country": "Global"},
    {"name": "SalesLoft", "careers_url": "https://salesloft.com/careers", "category": "cloud_saas", "country": "Global"},
    {"name": "Outreach", "careers_url": "https://outreach.io/careers", "category": "cloud_saas", "country": "Global"},
    {"name": "Plaid", "careers_url": "https://plaid.com/careers", "category": "cloud_saas", "country": "Global"},
    {"name": "Marqeta", "careers_url": "https://marqeta.com/careers", "category": "cloud_saas", "country": "Global"},
    {"name": "Unit", "careers_url": "https://unit.co/careers", "category": "cloud_saas", "country": "Global"},
    {"name": "Lithic", "careers_url": "https://lithic.com/careers", "category": "cloud_saas", "country": "Global"},
    {"name": "Gusto", "careers_url": "https://gusto.com/about/careers", "category": "cloud_saas", "country": "Global"},
    {"name": "Fivetran", "careers_url": "https://fivetran.com/careers", "category": "cloud_saas", "country": "Global"},
    {"name": "Hightouch", "careers_url": "https://hightouch.com/careers", "category": "cloud_saas", "country": "Global"},
    {"name": "Amplitude", "careers_url": "https://amplitude.com/careers", "category": "cloud_saas", "country": "Global"},
    {"name": "Mixpanel", "careers_url": "https://mixpanel.com/careers", "category": "cloud_saas", "country": "Global"},
    {"name": "Otter.ai", "careers_url": "https://otter.ai/careers", "category": "ai_companies", "country": "Global"},
    # Indian Fintech & Others
    {"name": "Upstox", "careers_url": "https://upstox.com/careers", "category": "fintech", "country": "India"},
    {"name": "Porter", "careers_url": "https://porter.in/careers", "category": "logistics", "country": "India"},
    {"name": "Navi", "careers_url": "https://navi.com/careers", "category": "fintech", "country": "India"},
    {"name": "Titan", "careers_url": "https://www.titan.co.in/careers", "category": "conglomerates", "country": "India"},
    {"name": "BlueStone", "careers_url": "https://bluestone.com/careers", "category": "ecommerce", "country": "India"},
    {"name": "Turtlemint", "careers_url": "https://turtlemint.com/careers", "category": "fintech", "country": "India"},
    {"name": "Instahyre", "careers_url": "https://instahyre.com/careers", "category": "hrtech", "country": "India"},
    {"name": "AngelList", "careers_url": "https://angellist.com/careers", "category": "hrtech", "country": "Global"},
    {"name": "Bounce", "careers_url": "https://bounce.co/careers", "category": "logistics", "country": "India"},
]


def seed_companies(db):
    """Seed the database with companies. Skips duplicates."""
    from models import Company
    added = 0
    seen_urls = set()
    for c in COMPANIES:
        if c["careers_url"] in seen_urls:
            continue
        seen_urls.add(c["careers_url"])
        existing = db.query(Company).filter_by(careers_url=c["careers_url"]).first()
        if not existing:
            db.add(Company(
                name=c["name"],
                careers_url=c["careers_url"],
                category=c.get("category", "other"),
                country=c.get("country", "India"),
                is_verified=True,
            ))
            added += 1
    db.commit()
    return added
